// Cloud Generator for Cloudflare (constitution sections 5, 47). An Extension, not Core.
// Emits configuration only (no code): a Workers static-assets config that serves <app>.uapp/web.
// Deterministic: a fixed compatibility date, no timestamps.

type Obj = Record<string, any>; // validated spec JSON

export const WEB_DIR = '../../web'; // relative to cloud/cloudflare/
export const COMPATIBILITY_DATE = '2025-01-01';

export function generate(specs: Obj): Record<string, string> {
  const ui = specs.ui_spec.ui_spec;
  return {
    'wrangler.toml': [
      '# Generated by Ion cloud-cloudflare. Serves the ui-web output of this .uapp as static assets.',
      'name = "ion-app"', `compatibility_date = "${COMPATIBILITY_DATE}"`, '', '[assets]', `directory = "${WEB_DIR}"`, '',
    ].join('\n'),
    'README.md': [
      '# Cloudflare', '',
      `Serves \`${WEB_DIR}\` (default locale: ${ui.default_locale}). From the root of this .uapp:`,
      '```bash', 'npx wrangler deploy --config cloud/cloudflare/wrangler.toml', '```',
      'You need a Cloudflare account and `wrangler login`. `web/index.html` shows nothing until your authentication layer supplies permissions; `web/demo.html` is in-memory preview data. Not deployed where this was generated.', '',
    ].join('\n'),
  };
}
