// The shapes of the Specs Ion Core produces (constitution sections 31-36).
// Specs are plain JSON: no SQL, no routes, no HTML (sections 37, 96).

import type { AttributeType } from './constitution.ts';

// ---------------------------------------------------------------- schema_spec (section 31)
export interface SpecColumn {
  name: string;
  type: AttributeType; // one of the 14 Ion types, never a platform type
  nullable: boolean;
  primary?: true;
  auto?: true; // value generated by the platform: uuid -> new id, timestamp -> now, date -> today
  unique?: true;
  default?: string | number | boolean;
  values?: string[]; // enum only
  scale?: number; // money only (default 2): the stored integer counts 10^-scale of the major unit
  system?: true; // generated by Ion (id, created_at, archived_at), not declared by the user
  transitions?: Record<string, string[]>; // enum only (metadata): allowed state changes
}

export interface SchemaTable {
  entity: string; // entity id
  name: string;
  type: string;
  table: string;
  columns: SpecColumn[];
  indexes: Array<{ columns: string[]; unique?: true }>;
  constraints: unknown[];
  security: { row_level: true };
  archivable: true; // law: nothing is deleted, only archived (archived_at)
  versioned?: true; // metadata: a `version` column and optimistic locking
}

export interface SchemaSpec { schema_spec: { tables: SchemaTable[] } }

// ---------------------------------------------------------------- relationship_spec (section 32)
export interface SpecApi {
  method: 'GET' | 'POST' | 'PATCH' | 'DELETE';
  path: string;
  operation: 'create' | 'read' | 'update' | 'delete';
  summary: string;
}

export interface RelationshipItem {
  id: string;
  from: string; // entity id
  to: string;
  type: string;
  cascade?: 'restrict' | 'archive'; // metadata: what archiving the referenced (or either linked) row does; absent = none
  storage: { table: string; columns: string[] };
  junction?: {
    table: string;
    columns: Array<{ name: string; references: string }>; // "students.id"
    attributes: SpecColumn[];
    unique: string[][]; // column sets, over non-archived rows only
    indexes: string[][];
    active_only: true;
  };
  foreign_key?: {
    table: string; // holder table
    column: string;
    references: string; // "professors.id"
    create_column: boolean; // false when the user already declared the uuid attribute
    unique: boolean; // one-to-one, over non-archived rows only
    index: boolean;
    attributes: Array<{ column: string; attribute: SpecColumn }>; // relationship attributes, stored on the holder
  };
  apis: SpecApi[];
}

export interface RelationshipSpec { relationship_spec: { relationships: RelationshipItem[] } }

// ---------------------------------------------------------------- event_spec (section 33)
export type Row = 'actor' | 'target';
export type SpecValue = string | number | boolean | null | unknown[] | { [k: string]: unknown } | { from: Row };

export type SpecTrigger =
  | { action: 'send_notification'; to: string; row: Row; message: string; channel?: string; template?: string }
  | { action: 'send_email'; to: string; row: Row; attribute: string; subject: string; body: string }
  | { action: 'increment' | 'decrement'; entity: string; attribute: string; field: string; row: Row; by: number }
  | { action: 'update_field'; entity: string; attribute: string; field: string; row: Row; value: SpecValue }
  | { action: 'create_entity'; entity: string; values: Record<string, SpecValue> }
  | { action: 'delete_entity'; entity: string; row: Row }
  | { action: 'log'; to: 'audit'; level?: string }
  | { action: 'call_webhook'; url: string }
  | { action: 'trigger_workflow'; workflow: string };

export interface EventItem {
  id: string;
  name: string;
  type: string;
  actor: string;
  target: string;
  relationship?: string;
  triggers: SpecTrigger[];
  rate?: { max: number; per_seconds: number }; // metadata: at most `max` runs per `per_seconds`
  compensations: unknown[]; // reserved by section 33; always empty in 3.0.0
}

export interface SystemRecord {
  fields: Array<{ name: string; type: AttributeType; nullable: boolean }>;
  append_only: boolean;
}

export interface EventSpec {
  event_spec: {
    events: EventItem[];
    // Durable records every platform must provide once events exist (laws: all events logged, audited, notified).
    system_records?: { ledger: SystemRecord; audit: SystemRecord; notifications: SystemRecord };
  };
}

// ---------------------------------------------------------------- ui_spec (section 34)
export interface UiField {
  name: string;
  type: AttributeType;
  widget: string; // text | number | integer | money | checkbox | date | datetime | email | url | tel | json | select | relation
  required: boolean;
  auto: boolean;
  labels: { en: string; ar?: string };
  values?: string[];
  scale?: number; // money: decimal places of the major unit (display and input only; the stored value is whole minor units)
  target?: string; // relation: entity id
  relationship?: string;
  label_entity?: string; // relation label falls back to this entity's label
  system?: true;
}

export interface UiRelation {
  relationship: string;
  side: 'from' | 'to';
  other: string; // entity id
  type: string;
  many: boolean;
  title: { entity?: string; text?: string; reverse?: boolean; suffix?: string };
  attributes: UiField[];
  paths: { list: string; create: string; update: string; delete: string };
}

export interface UiDataSource {
  id: string; // "students"
  entity: string;
  labels: { en: { singular: string; plural: string }; ar?: { singular: string; plural: string } };
  display: string | null;
  fields: UiField[];
  relations: UiRelation[];
  filters: Array<{ field: string; kind: 'select' | 'boolean' | 'range'; type?: string; values?: string[] }>;
  search_fields: string[];
  surfaces: { notifications: boolean; activity: boolean };
  api: Record<'list' | 'create' | 'read' | 'update' | 'archive' | 'notifications' | 'activity', { method: string; path: string } | undefined>;
}

export interface UiPage {
  id: string;
  title: string;
  labels: { en: string; ar?: string };
  type: 'list' | 'detail' | 'form';
  mode?: 'create' | 'edit';
  data_source: string;
  path: string;
  columns?: string[];
  layout?: 'table';
  actions?: string[];
  pagination?: { size: number };
  search?: boolean;
  filters?: string[];
  fields?: string[];
  submit_action?: string;
  permission: string;
  // U12-U16, U19 (all optional so older ui_specs still load; rules.ts requires them on lists/details)
  sort?: { field: string; direction: 'asc' | 'desc' };
  page_sizes?: number[];
  confirm?: string[];
  states?: Record<'empty' | 'loading' | 'error', { labels: { en: string; ar?: string } }>;
  responsive?: { compact: 'cards' | 'table'; regular: 'cards' | 'table' };
  breadcrumb?: string[];
}

export interface UiSpec {
  ui_spec: {
    locales: string[];
    default_locale: string;
    pages: UiPage[];
    data_sources: UiDataSource[];
    events: Array<{ id: string; labels: { en: string; ar?: string }; type: string }>;
    navigation: { type: 'sidebar'; items: string[] };
    dashboard: { path: string; widgets: Array<{ kind: 'count'; data_source: string; permission: string; labels: { en: string; ar?: string } }> }; // U11
    directions: Record<string, 'rtl' | 'ltr'>; // U18
    theme: { primary_color: string; density: string };
    permissions: string[];
  };
}

export interface SpecSet {
  schema_spec: SchemaSpec;
  relationship_spec: RelationshipSpec;
  event_spec: EventSpec;
  ui_spec: UiSpec;
}
